name: Deploy to Server

on:
  push:
    branches:
      - main  # mainブランチにプッシュされたときに実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known_hosts
      run: |
        ssh-keyscan -H v2008.coreserver.jp >> ~/.ssh/known_hosts

    - name: Install Dependencies
      run: |
        npm install

    - name: Build Project
      run: |
        NODE_ENV=production npm run build  # Next.jsアプリケーションをプロダクションモードでビルド

    - name: Deploy to server
      run: |
        rsync -avz --progress -e "ssh -o StrictHostKeyChecking=no" --exclude='.git' --exclude='.github' --delete ./out/ onokoro@v2008.coreserver.jp:~/domains/onokoro-creation.com/public_html/collecture/
