name: Deploy to Server

on:
  push:
    branches:
      - main  # mainブランチにプッシュされたときに実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
    - name: Install Dependencies
      run: |
        npm install
        npm run build  # Next.jsアプリケーションをビルド

    - name: Deploy built files to server
      run: |
        rsync -avz --exclude='.git' --exclude='.github' --delete .next onokoro@v2008.coreserver.jp:~/public_html/collecture/.next
        rsync -avz --exclude='.git' --exclude='.github' --delete public onokoro@v2008.coreserver.jp:~/public_html/collecture/public
        rsync -avz --exclude='.git' --exclude='.github' --delete package.json onokoro@v2008.coreserver.jp:~/public_html/collecture/
